const canvas = document.getElementById('gameCanvas');
const ctx = canvas.getContext('2d');
const W = canvas.width, H = canvas.height;
const keys = {};
let running = false, soundOn = true, lastTime = 0, elapsed = 0, score = 0, hearts = 3, collected = 0;
const world = { width: 3300, camera: 0 };
const player = { x: 110, y: 500, w: 38, h: 54, vx: 0, vy: 0, grounded: false, invincible: 0, boost: 0 };
const platforms = [
  { x: 0, y: 636, w: 560, h: 84 }, { x: 670, y: 636, w: 430, h: 84 }, { x: 1190, y: 636, w: 430, h: 84 }, { x: 1700, y: 636, w: 540, h: 84 }, { x: 2310, y: 636, w: 990, h: 84 },
  { x: 315, y: 520, w: 170, h: 25 }, { x: 735, y: 470, w: 150, h: 25 }, { x: 970, y: 555, w: 130, h: 25 }, { x: 1270, y: 485, w: 170, h: 25 }, { x: 1510, y: 400, w: 160, h: 25 }, { x: 1840, y: 520, w: 160, h: 25 }, { x: 2110, y: 450, w: 170, h: 25 }, { x: 2470, y: 530, w: 180, h: 25 }, { x: 2750, y: 430, w: 170, h: 25 }
];
const coins = [315, 365, 415, 755, 805, 985, 1035, 1280, 1330, 1540, 1880, 2150]..map((x, i) => ({ x, y: [475,475,475,425,425,510,510,440,440,355,475,405][i], got: false, bob: i }));
const enemies = [{ x: 420, y: 580, w: 38, h: 32, min: 250, max: 530, vx: 55, alive: true }, { x: 790, y: 438, w: 35, h: 32, min: 735, max: 850, vx: 45, alive: true }, { x: 1420, y: 604, w: 42, h: 32, min: 1200, max: 1580, vx: 60, alive: true }, { x: 1990, y: 488, w: 38, h: 32, min: 1850, max: 1990, vx: 48, alive: true }, { x: 2500, y: 598, w: 42, h: 32, min: 2320, max: 2700, vx: 54, alive: true }];
const spikes = [{ x: 565, y: 612, w: 75, h: 24 }, { x: 1115, y: 612, w: 65, h: 24 }, { x: 1630, y: 612, w: 60, h: 24 }, { x: 2245, y: 612, w: 55, h: 24 }];
const powerup = { x: 2200, y: 390, w: 28, h: 28, got: false };
const finish = { x: 3100, y: 530, w: 45, h: 106 };

function reset() { Object.assign(player, { x: 110, y: 500, vx: 0, vy: 0, grounded: false, invincible: 0, boost: 0 }); world.camera = 0; elapsed = 0; score = 0; hearts = 3; collected = 0; coins.forEach(c => c.got = false); enemies.forEach(e => e.alive = true); powerup.got = false; updateHud(); }
function start() { reset(); running = true; document.getElementById('startScreen').classList.add('hidden'); document.getElementById('endScreen').classList.add('hidden'); lastTime = performance.now(); requestAnimationFrame(loop); }
function end(won) { running = false; document.getElementById('resultBadge').textContent = won ? '✦' : '!'; document.getElementById('resultEyebrow').textContent = won ? 'JUNGLE CLEARED' : 'THE JUNGLE BIT BACK'; document.getElementById('resultTitle').textContent = won ? 'You found the chest!' : 'Keep your eyes up.'; document.getElementById('resultText').textContent = won ? 'The Greenwild remembers a brave explorer.' : 'Every great run has a few wild landings.'; document.getElementById('finalScore').textContent = String(score).padStart(6, '0'); document.getElementById('finalCoins').textContent = `${collected} / ${coins.length}`; document.getElementById('endScreen').classList.remove('hidden'); }
function updateHud() { document.getElementById('coinCount').textContent = `${collected} / ${coins.length}`; document.getElementById('scoreCount').textContent = String(score).padStart(6, '0'); document.getElementById('heartCount').textContent = hearts; const seconds = Math.floor(elapsed); document.getElementById('timer').textContent = `${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`; }
function overlaps(a, b) { return a.x < b.x + b.w && a.x + a.w > b.x && a.y < b.y + b.h && a.y + a.h > b.y; }
function hurt() { if (player.invincible > 0) return; hearts--; player.invincible = 1.4; player.vy = -430; player.vx = -player.vx || -140; if (hearts <= 0) end(false); updateHud(); }
function update(dt) {
  elapsed += dt; player.invincible = Math.max(0, player.invincible - dt); player.boost = Math.max(0, player.boost - dt);
  const direction = (keys.ArrowRight || keys.d ? 1 : 0) - (keys.ArrowLeft || keys.a ? 1 : 0); const speed = player.boost ? 330 : 245; player.vx += (direction * speed - player.vx) * Math.min(1, dt * 10); if (!direction) player.vx *= .82;
  if ((keys[' '] || keys.ArrowUp|keys.w) && player.grounded) { player.vy = -590; player.grounded = false; keys[' '] = false; keys.ArrowUp = false; }
  player.vy += 1450 * dt; const oldY = player.y; player.x += player.vx * dt; player.y += player.vy * dt; player.x = Math.max(0, Math.min(world.width - player.w, player.x)); player.grounded = false;
  platforms.forEach(p => { if (player.x + player.w > p.x && player.x < p.x + p.w && oldY + player.h <= p.y && player.y + player.h >= p.y && player.vy >= 0) { player.y = p.y - player.h; player.vy = 0; player.grounded = true; } });
  coins.forEach(c => { if (!c.got && overlaps(player, { x: c.x - 13, y: c.y - 13, w: 26, h: 26 })) { c.got = true; collected++; score += 100; updateHud(); } });
  if (!powerup.got && overlaps(player, powerup)) { powerup.got = true; player.boost = 8; score += 250; updateHud(); }
  enemies.forEach(e => { if (!e.alive) return; e.x += e.vx * dt; if (e.x < e.min || e.x > e.max) e.vx *= -1; if (overlaps(player, e)) { if (player.vy > 80 && player.y + player.h - e.y < 24) { e.alive = false; player.vy = -390; score += 200; updateHud(); } else hurt(); } });
  spikes.forEach(s => { if (overlaps(player, s)) hurt(); }); if (player.y > H + 80) { hurt(); player.x = Math.max(40, player.x - 170); player.y = 430; }
  if (overlaps(player, finish)) end(true); world.camera += (player.x - world.camera - 360) * Math.min(1, dt * 4); world.camera = Math.max(0, Math.min(world.width - W, world.camera)); updateHud();
}
function draw() { ctx.clearRect(0, 0, W, H); drawBackground(); ctx.save(); ctx.translate(-world.camera, 0); platforms.forEach(drawPlatform); spikes.forEach(drawSpikes); coins.forEach(drawCoin); if (!powerup.got) drawPowerup(); enemies.forEach(drawEnemy); drawFinish(); drawPlayer(); ctx.restore(); }
function drawBackground() { const g = ctx.createLinearGradient(0, 0, 0, H); g.addColorStop(0, '#6bb6a2'); g.addColorStop(1, '#c7d98d'); ctx.fillStyle = g; ctx.fillRect(0, 0, W, H); ctx.fillStyle = 'rgba(232,244,192,.45)'; ctx.beginPath(); ctx.arc(1050 - world.camera * .15, 130, 95, 0, Math.PI * 2); ctx.fill(); for (let i = -1; i < 16; i++) { const x = i * 260 - (world.camera * .18 % 260); ctx.fillStyle = i % 2 ? '#4b9d83' : '#3c8a76'; ctx.beginPath(); ctx.moveTo(x, 590); ctx.lineTo(x + 80, 250); ctx.lineTo(x + 210, 590); ctx.fill(); ctx.fillStyle = 'rgba(31,99,80,.45)'; ctx.fillRect(x + 35, 280, 9, 350); } }
function drawPlatform(p) { ctx.fillStyle = '#72533e'; ctx.fillRect(p.x, p.y, p.w, p.h); ctx.fillStyle = '#345d45'; ctx.fillRect(p.x, p.y, p.w, 12); ctx.fillStyle = '#6e9d53'; for (let x = p.x + 8; x < p.x + p.w; x += 32) { ctx.fillRect(x, p.y - 5, 19, 5); } }
function drawSpikes(s) { ctx.fillStyle = '#263d39'; for (let x = s.x; x < s.x + s.w; x += 18) { ctx.beginPath(); ctx.moveTo(x, s.y + s.h); ctx.lineTo(x + 9, s.y); ctx.lineTo(x + 18, s.y + s.h); ctx.fill(); } }
function drawCoin(c) { if (c.got) return; const y = c.y + Math.sin(elapsed * 4 + c.bob) * 5; ctx.fillStyle = '#e9b83f'; ctx.beginPath(); ctx.arc(c.x, y, 13, 0, Math.PI * 2); ctx.fill(); ctx.strokeStyle = '#fff0a3'; ctx.lineWidth = 3; ctx.stroke(); ctx.fillStyle = '#fff0a3'; ctx.fillRect(c.x - 2, y - 7, 4, 14); }
function drawPowerup() { const y = powerup.y + Math.sin(elapsed * 3) * 7; ctx.fillStyle = '#f27654'; ctx.fillRect(powerup.x, y, powerup.w, powerup.h); ctx.fillStyle = '#fff4d1'; ctx.font = 'bold 18px Manrope'; ctx.fillText('S', powerup.x + 7, y + 21); }
function drawEnemy(e) { if (!e.alive) return; ctx.fillStyle = '#d9574b'; ctx.beginPath(); ctx.roundRect(e.x, e.y, e.w, e.h, 12); ctx.fill(); ctx.fillStyle = '#fff1cf'; ctx.fillRect(e.x + 8, e.y + 9, 7, 7); ctx.fillRect(e.x + 24, e.y + 9, 7, 7); ctx.fillStyle = '#203e39'; ctx.fillRect(e.x + 10, e.y + 11, 3, 3); ctx.fillRect(e.x + 26, e.y + 11, 3, 3); }
function drawFinish() { ctx.fillStyle = '#324f41'; ctx.fillRect(finish.x, finish.y, 7, finish.h); ctx.fillStyle = '#f27654'; ctx.beginPath(); ctx.moveTo(finish.x + 7, finish.y + 5); ctx.lineTo(finish.x + 57, finish.y + 22); ctx.lineTo(finish.x + 7, finish.y + 38); ctx.fill(); ctx.fillStyle = '#f7d85a'; ctx.fillRect(finish.x - 7, finish.y + finish.h - 7, 22, 7); }
function drawPlayer() { if (player.invincible > 0 && Math.floor(player.invincible * 12) % 2 === 0) return; const x = player.x, y = player.y; ctx.fillStyle = '#e7a65a'; ctx.beginPath(); ctx.arc(x + 19, y + 15, 14, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#173d39'; ctx.fillRect(x + 6, y + 25, 27, 27); ctx.fillStyle = '#f27654'; ctx.fillRect(x + 3, y + 3, 33, 9); ctx.fillStyle = '#fff0ce'; ctx.fillRect(x + 21, y + 13, 5, 5); ctx.fillStyle = '#173d39'; ctx.fillRect(x + 22, y + 14, 2, 2); ctx.fillStyle = '#f7d85a'; ctx.fillRect(x + 7, y + 51, 10, 4); ctx.fillRect(x + 25, y + 51, 10, 4); if (player.boost) { ctx.strokeStyle = '#f27654'; ctx.lineWidth = 3; ctx.beginPath(); ctx.arc(x + 19, y + 27, 30 + Math.sin(elapsed * 8) * 3, 0, Math.PI * 2); ctx.stroke(); } }
function loop(time) { if (!running) return; const dt = Math.min(.033, (time - lastTime) / 1000); lastTime = time; update(dt); draw(); requestAnimationFrame(loop); }
window.addEventListener('keydown', e => { if (['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight', ' '].includes(e.key)) e.preventDefault(); keys[e.key] = true; }); window.addEventListener('keyup', e => keys[e.key] = false);
document.getElementById('playButton').onclick = start; document.getElementById('againButton').onclick = start; document.getElementById('restartButton').onclick = start; document.getElementById('soundButton').onclick = e => { soundOn = !soundOn; e.currentTarget.textContent = soundOn ? '♫' : '×'; e.currentTarget.setAttribute('aria-label', soundOn ? 'Mute sound' : 'Enable sound'); };
draw();
